[package]
name = "pig"
version = "0.1.0"
edition = "2021"

[dependencies]
my_library = { package = "my_library", path = "../my_library", features = [
  "locking",
] }
bevy = "0.12"
bevy_egui = "0.23"
